### PR TITLE
Add sf3 compat for expression language

### PR DESCRIPTION
**Pull request by lucascourot**
Sf3 requires symfony/expression-language ~3.0 https://github.com/symfony/symfony/blob/master/composer.json#L44

### CODE REVIEW

**Comment by jibe84** [comment]
:+1:

**Comment by Oliboy50** [comment]
if you could do it for `"symfony/yaml": "~2.3|~3.0"` too :)

**Comment by Oliboy50** [comment]
👍

**Comment by b-viguier** [comment]
👍

**Pull request merged**
